name: deploy-auth
on: 
  push:
    branches:
      - master
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/actions@v2
      - run: cd auth && docker build -t dibyn7/auth .
      
      
